services:
  loki-staging:
    image: grafana/loki:latest
    container_name: loki-staging
    ports:
      - "3300:3100"  # Updated port to avoid conflict
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-staging-data:/loki
    networks:
      - monitoring-staging

  grafana-staging:
    image: grafana/grafana:latest
    container_name: grafana-staging
    ports:
      - "3101:3101"  # Updated port to avoid conflict
    env_file:
      - .env.staging
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana-staging-data:/var/lib/grafana
      - ./grafana-staging.ini:/etc/grafana/grafana.ini
    depends_on:
      - loki-staging
    networks:
      - monitoring-staging

  promtail-staging:
    image: grafana/promtail:2.7.1
    container_name: promtail-staging
    volumes:
      - ./promtail-staging-config.yaml:/etc/promtail/config.yml
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers  # Mount the Docker logs
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring-staging

volumes:
  grafana-staging-data:
  loki-staging-data:

networks:
  monitoring-staging:
    driver: bridge
