global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'alert.rules.yml'

alerting:
  alertmanagers:
    - static_configs:
      - targets: ["alertmanager:9093"]
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus-metrics:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter-metrics:9100']


