name: ONDC Automation Monitoring Service Deployment

on:

  push:
    branches: ["release-staging"]
  workflow_dispatch:

jobs:
  ssh-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH Setup and Cloning Repository
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./key.pem
          chmod 600 ./key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

          ssh -i ./key.pem ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} -T <<EOF
          REPO_DIR=~/ONDC-automation-framework-staging/automation-monitoring
          echo "Removing existing repository directory if exists"
          sudo docker-compose -f $REPO_DIR/docker-compose-staging.yml down || true
          sudo rm -rf \$REPO_DIR || true
          echo "Cloning repository from main branch"
          git clone --single-branch --branch release-staging https://github.com/ONDC-Official/automation-monitoring.git \$REPO_DIR
          EOF

      - name: Install Docker Compose (if not installed)
        run: |
          ssh -i ./key.pem ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} <<EOF
          # Check if Docker Compose is installed
          if ! command -v docker-compose &> /dev/null
          then
            echo "Docker Compose not found. Installing..."
            sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          else
            echo "Docker Compose is already installed."
          fi
          EOF

      - name: Write secrets to .env.staging on EC2
        run: |
          echo "Writing secrets to .env.staging file"
          ssh -i ./key.pem ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} <<EOF
          REPO_DIR=~/ONDC-automation-framework-staging/automation-monitoring
          echo "Writing environment variables to .env.staging file"
          echo "GRAFANA_USER=${{ secrets.GRAFANA_USER }}" >> \$REPO_DIR/.env.staging
          echo "GRAFANA_PASSWORD=${{ secrets.GRAFANA_PASSWORD }}" >> \$REPO_DIR/.env.staging
          EOF

      - name: Verify .env.staging and docker-compose-staging.yml files
        run: |
          ssh -i ./key.pem ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} <<EOF
          REPO_DIR=~/ONDC-automation-framework-staging/automation-monitoring
          # Check if .env.staging and docker-compose-staging.yml files exist
          if [ ! -f \$REPO_DIR/.env.staging ]; then
            echo ".env.staging file not found in \$REPO_DIR!"
            exit 1
          fi
          if [ ! -f \$REPO_DIR/docker-compose-staging.yml ]; then
            echo "docker-compose-staging.yml file not found in \$REPO_DIR!"
            exit 1
          fi
          echo ".env.staging and docker-compose-staging.yml files found."
          EOF

      - name: Automation Monitoring Service Deployment
        run: |
          echo "Deploying with Docker Compose"
          ssh -i ./key.pem ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} <<EOF
          REPO_DIR=~/ONDC-automation-framework-staging/automation-monitoring
          cd \$REPO_DIR

          # Ensure the .env.staging and docker-compose-staging.yml files exist
          if [ ! -f .env.staging ]; then
            echo ".env.staging file not found!"
            exit 1
          fi

          if [ ! -f docker-compose-staging.yml ]; then
            echo "docker-compose-staging.yml file not found!"
            exit 1
          fi

          # Start the containers using Docker Compose
          echo "Running docker-compose up -d --build"
          sudo docker compose -f docker-compose-staging.yml up -d --build
          EOF
